# %ECSV 0.9
# ---
# datatype:
# - {name: obj_id, datatype: string}
# - {name: band_set, datatype: string}
# - {name: source, datatype: string}
# - {name: pre_max, datatype: int64}
# - {name: post_max, datatype: int64}
# - {name: z, datatype: float64}
# - {name: t0, datatype: float64}
# - {name: x0, datatype: float64}
# - {name: x1, datatype: float64}
# - {name: c, datatype: float64}
# - {name: z_err, datatype: float64}
# - {name: t0_err, datatype: float64}
# - {name: x0_err, datatype: float64}
# - {name: x1_err, datatype: float64}
# - {name: c_err, datatype: float64}
# - {name: chisq, datatype: float64}
# - {name: ndof, datatype: float64}
# - {name: b_max, datatype: float64}
# - {name: delta_15, datatype: float64}
# - {name: message, datatype: string}
# meta: !!omap
# - band_names: !!python/tuple [csp_dr3_u, csp_dr3_g, csp_dr3_r, csp_dr3_i, csp_dr3_B, csp_dr3_V0, csp_dr3_V1, csp_dr3_V, csp_dr3_Y, csp_dr3_J,
#     csp_dr3_Jrc2, csp_dr3_H, csp_dr3_Ydw, csp_dr3_Jdw, csp_dr3_Hdw]
# - lambda_eff: !!python/tuple [3639.3, 4765.1, 6223.3, 7609.2, 4350.6, 5369.6, 5401.4, 5375.2, 10350.8, 12386.5, 12356.3, 16297.7, 10439.8,
#     12383.2, 16282.8]
# - {fit_func: simple_fit}
# - vparams: [t0, x0, x1, c]
# - {timeout_sec: 90}
# - {out_path: /Users/daniel/Github/SDSS-Classification/results/csp_dr3_simple_fit_fits.ecsv}
# schema: astropy-2.0
obj_id band_set source pre_max post_max z t0 x0 x1 c z_err t0_err x0_err x1_err c_err chisq ndof b_max delta_15 message
2004dt "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.018830    t0 = +2453240.000000    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 192, in _flux    flux = amplitude * np.interp(x1, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2004ef "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.029790    t0 = +2453267.917584    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 192, in _flux    flux = amplitude * np.interp(x1, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2004eo "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.014750    t0 = +2453278.272669    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 188, in _flux    flux = amplitude * np.interp(c, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2004ey "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.014640    t0 = +2453304.035080    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 188, in _flux    flux = amplitude * np.interp(c, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2004gc "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.030740    t0 = +2453315.000000    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 192, in _flux    flux = amplitude * np.interp(x1, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2004gs "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.027520    t0 = +2453346.000000    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 188, in _flux    flux = amplitude * np.interp(c, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2004gu "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.046930    t0 = +2453354.000000    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 192, in _flux    flux = amplitude * np.interp(x1, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2005A "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.018350    t0 = +2453381.000000    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 192, in _flux    flux = amplitude * np.interp(x1, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2005M "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.025600    t0 = +2453406.931360    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 192, in _flux    flux = amplitude * np.interp(x1, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2005W "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.007960    t0 = +2453422.000000    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 192, in _flux    flux = amplitude * np.interp(x1, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2005ag "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.080400    t0 = +2453404.000000    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 188, in _flux    flux = amplitude * np.interp(c, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2005al "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.013290    t0 = +2453430.000000    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 188, in _flux    flux = amplitude * np.interp(c, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2005am "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.008970    t0 = +2453440.916609    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 192, in _flux    flux = amplitude * np.interp(x1, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2005be "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.035620    t0 = +2453460.000000    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 188, in _flux    flux = amplitude * np.interp(c, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2005bg "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.024170    t0 = +2453465.000000    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 188, in _flux    flux = amplitude * np.interp(c, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2005bl "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.025130    t0 = +2453485.115136    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 192, in _flux    flux = amplitude * np.interp(x1, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2005bo "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.015020    t0 = +2453474.000000    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 192, in _flux    flux = amplitude * np.interp(x1, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2005el "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.014900    t0 = +2453646.603260    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 192, in _flux    flux = amplitude * np.interp(x1, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2005eq "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "exception was raised in user functionUser function arguments:     z = +0.028370    t0 = +2453649.000000    x0 = +0.000000    x1 = +0.650000     c = +1.000000Original python exception in user function:ValueError: object too deep for desired array  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/fitting.py"", line 44, in chisq    zp=data.zp, zpsys=data.zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1400, in bandflux    raise e  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1397, in bandflux    return _bandflux(self, band, time, zp, zpsys)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 152, in _bandflux    fsum = _bandflux_single(model, b, time_or_phase[mask])  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 114, in _bandflux_single    f = model._flux(time_or_phase, wave)  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/sncosmo/models.py"", line 1272, in _flux    f = a * self._source._flux(phase, restwave)  File ""/Users/daniel/Github/SDSS-Classification/phot_class/models/_sources.py"", line 192, in _flux    flux = amplitude * np.interp(x1, self._stretch[c_index], flux)  File ""<__array_function__ internals>"", line 6, in interp  File ""/anaconda3/envs/phot_class/lib/python3.7/site-packages/numpy/lib/function_base.py"", line 1412, in interp    return interp_func(x, xp, fp, left, right)"
2005gj "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "Encountered unspecified value for z in prior: {}"
